apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: metrics
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{.Values.env }}-metrics-http-server
  type: ClusterIP