replicas: 1
name: telegraf-int-metrics

resources:
  requests:
    cpu: 0.1
    memory: "200Mi"
  limits:
    cpu: 0.2
    memory: "200Mi"

env:
  ENV: "int"
  TELEGRAF_MS_TAG: "metrics"
  TELEGRAF_DC_TAG: "wz-ams"
  TELEGRAF_ENV_TAG: "int"
  TELEGRAF_DB: "metrics"
  TELEGRAF_USER: "metrics"
  TELEGRAF_PASSWD: "somepass"
  TELEGRAF_RP: "onemonth"
  TELEGRAF_NAMEPASS: "\"metrics-*\""

hpa:
  targetCPU: 70 # При какой утилизации CPU добавлять инстанс
  minReplica: 1
  maxReplica: 10