apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  ports:
  - protocol: UDP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
